### ISSUE TITLE
Uwagi do API 

### ISSUE THREAD

**Issue by Rippp** [pw-software-engineering/2022_specification#2]
- AuthData zamienić nazwę lastName na password
- client/register brakuje password przy rejestracji w requestBody (można dodać po prostu pole password do schema Client)
- Wykonując zapytanie GET pod producer/orders nie otrzymujemy dietID w obiekcie diets, przez co nie jesteśmy w stanie potem odwołać się do szczegółów danej diety na dites/{diet-id}. Proponujemy, żeby następujące schema miały pole zawierające identyfikator obiektu w sobie: Complaint, Order, Diet, Meal
- zmiana nazwa endpointu diet/ na diets/, meal/ na meals/, 
- Wykonując zapytanie GET pod diet/ powinniśmy otrzymać array zawierający wiele Diet, a nie pojedynczy obiekt Diet
- Description w responses na endpoint diet/ są błędne (nie zgadzają się z description endpointu) 
- Wykonując zapytanie POST pod diet/ i PUT pod diet/{diet-id} wywalić calories i vegan z requestBody (te wartości obliczamy na podstawie Meal'i)
- zamienić dietId, orderId itd. z integera na string (aby udostępnić możliwość używania GUID)
- tam gdzie odwołujemy się do jakiegoś konretnego obiektu po jego id, proponujemy zwracanie http 404 gdy obiekt o podanym id nie istnieje

**Comment by michalmuzyka** [comment]
Poprawiono
